name = "CARM"
authors = ["Guilherme Araújo", "Roger Behling", "Yunier Bello-Cruz", "Luiz-Rafael Santos"]

[deps]
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
DrWatson = "634d3b9d-ee7a-5ddf-bec9-22491ea816e1"
PolynomialRoots = "3a141323-8675-5d76-9d11-e1df1406c778"
ProximalOperators = "a725b495-10eb-56fe-b38b-717eba820537"

[compat]
julia = "1.5.3"
